import{a as w,S as v,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const S="51754345-9cee8d21a0c191975c57a35c9",q="https://pixabay.com/api/";async function m(a,t=1,r=15){const i={key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r};return(await w.get(q,{params:i})).data}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(a){const t=a.map(r=>`
        <li class="gallery-item">
          <a href="${r.largeImageURL}">
            <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${r.likes}</p>
            <p><b>Views:</b> ${r.views}</p>
            <p><b>Comments:</b> ${r.comments}</p>
            <p><b>Downloads:</b> ${r.downloads}</p>
          </div>
        </li>
      `).join("");y.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){y.innerHTML=""}function p(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}const L=document.querySelector(".button-load");function $(){L.classList.remove("hidden")}function u(){L.classList.add("hidden")}const M=document.querySelector(".form"),E=document.querySelector(".button-load");let c="",n=1;const l=15;let f=0;M.addEventListener("submit",async a=>{if(a.preventDefault(),c=a.target.elements["search-text"].value.trim(),!c){s.warning({message:"Please enter a search term!"});return}n=1,u(),B(),p();try{const t=await m(c,n,l);if(f=t.totalHits,t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(t.hits),f>l?$():(u(),s.info({message:"We're sorry, but you've reached the end of search results."}))}catch{s.error({message:"Something went wrong. Please try again later."})}finally{b()}});E.addEventListener("click",async()=>{n+=1,p();try{const a=await m(c,n,l);g(a.hits);const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),n*l>=f&&(u(),s.info({message:"We're sorry, but you've reached the end of search results."}))}catch{s.error({message:"Something went wrong. Please try again later."})}finally{b()}});
//# sourceMappingURL=index.js.map
