import{a as b,S as w,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const v="51754345-9cee8d21a0c191975c57a35c9",S="https://pixabay.com/api/";async function u(a,r=1,e=15){const i={key:v,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:e};return(await b.get(S,{params:i})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(a){const r=a.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",r),q.refresh()}function P(){f.innerHTML=""}function h(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}const g=document.querySelector(".button-load");function B(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}const $=document.querySelector(".form"),M=document.querySelector(".button-load");let E="",s=1;const c=15;let d=0;$.addEventListener("submit",async a=>{a.preventDefault();const r=a.target.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search term!"});return}s=1,L(),P(),h();try{const e=await u(r,s,c);if(d=e.totalHits,e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(e.hits),d>c&&B()}catch{n.error({message:"Something went wrong. Please try again later."})}finally{p()}});M.addEventListener("click",async()=>{s+=1,h();try{const a=await u(E,s,c);y(a.hits);const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),s*c>=d&&(L(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong. Please try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
